PATHS:
  RATINGS: "./data/processed/ratings.parquet"
  MOVIES: "./data/processed/movies.parquet"
  USERS: "./data/processed/users.parquet"
SEED: 42
TRAIN_VAL_RATIO: 0.8
MODEL:
  BATCH_SIZE: 2048
  USER_EMBEDDING_DIM: 20
  USER_AGE_EMBEDDING_DIM: 5
  USER_GENDER_EMBEDDING_DIM: 5
  MOVIE_EMBEDDING_DIM: 10
  MOVIE_CAT_EMBEDDING_DIM: 20
  LEARNING_RATE: 1e-2
  DROPOUT: 0.2
MAX_EPOCHS: 50
